version: '3.1'

services:
  vejice_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - vejice_db_data:/var/lib/postgresql/data

volumes:
  vejice_db_data:
